### ISSUE TITLE
SDM Lesson NA Values from Raster Extract

### ISSUE THREAD

**Issue by milapruiett** [BiodiversityDataScienceCorp/SDM#2]
NA values produced with raster::extract in S### Section 3: Collate Env Data and Point Data into Proper Model Formats ###  lines 70 - 73.

**Comment by jcoliver** [comment]
Which file is this happening?

**Comment by milapruiett** [comment]
SDM_maxent_lesson.R

Thank you!

**Comment by jcoliver** [comment]
This is most likely due to observation points that lie in areas without climate raster data. Usually this happens with observations with lat/long coordinates that put them in the ocean. Skipping the call to `na.omit()` in the script to:
```
occEnv <- raster::extract(x = clim, y = ranaDataNotCoords)
# Find which rows had missing data and create a column in the original data to indicate this
ranaDataNotCoords$missing <- is.na(occEnv[, 1])
# Plot data, using different colors to indicate missing or not
plot(x = ranaDataNotCoords$longitude, 
     y = ranaDataNotCoords$latitude, 
     col = ranaDataNotCoords$missing + 1) # not missing = black, missing = pink
```
Which should show that those NA values are due to the rare, elusive, marine-adapted _R. marinus_. Or they are just points recorded with inaccurate lat/long and should be tossed before building SDM. :)
![image](https://user-images.githubusercontent.com/1939813/220796745-ff9d93c7-81d6-46fe-91d7-683066c0dd95.png)
